Update

diff --git a/.github/workflows/push-frontend.yaml b/.github/workflows/push-frontend.yaml
--- a/.github/workflows/push-frontend.yaml
+++ b/.github/workflows/push-frontend.yaml
@@ -29,8 +29,8 @@ jobs:
               ls -R ./frontend-code/
         - name: "Copy files to S3 bucket"
           run: | 
-              aws s3 cp ./frontend-code/ s3://${{env.BUCKET_NAME}}/ --exclude ".git*" || echo "Error copying files to s3"
+              aws s3 cp ./frontend-code/ s3://${{env.BUCKET_NAME}}/ --recursive --exclude ".git*" || echo "Error copying files to s3"
         - name: "Debug: List files in s3 bucket"
           run: |
-              aws s3 ls -R s3://${{env.BUCKET_NAME}}/
+              aws s3 ls s3://${{env.BUCKET_NAME}}/
 
